### ISSUE TITLE
预算抢占机制

### ISSUE THREAD

**Issue by zhaoyao91** [tap4fun/ai_sad4#65]
- 隔离血量系统，血量系统仅成为一个评估系统，不带主观操作
- 之前的根据血量关广告的机制做成基于血量的扩展机制
- 修改预算关闭机制为预算抢占机制
  - 当预算达到限制时，从father处申请下一笔预算
  - 如果father手中预算不够，则按血量排序，将血量最低的广告杀死，拿回预算
  - 如果杀到自己所在的级别，预算还是不够，则只好关闭自己了

**Comment by ppzz** [comment]
DONE

[1.1.0](https://github.com/tap4fun/ai_sad4/releases/tag/1.1.0)
